### ISSUE TITLE
Plugin doesn't work with Django 1.8

### ISSUE THREAD

**Issue by mrsarm** [aldryn/aldryn-bootstrap3#32]
When i try to execute ``python manage.py migrate``, I get this:

    Traceback (most recent call last):
      File "./manage.py", line 32, in <module>
        execute_from_command_line(sys.argv)
      File "/projects/mrsarm/py/mrdev/env2.7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
        utility.execute()
      File "/projects/mrsarm/py/mrdev/env2.7/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/projects/mrsarm/py/mrdev/env2.7/local/lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/projects/mrsarm/py/mrdev/env2.7/local/lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
        output = self.handle(*args, **options)
      File "/projects/mrsarm/py/mrdev/env2.7/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 93, in handle
        executor = MigrationExecutor(connection, self.migration_progress_callback)
      File "/projects/mrsarm/py/mrdev/env2.7/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 19, in __init__
        self.loader = MigrationLoader(self.connection)
      File "/projects/mrsarm/py/mrdev/env2.7/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 47, in __init__
        self.build_graph()
      File "/projects/mrsarm/py/mrdev/env2.7/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 312, in build_graph
        _reraise_missing_dependency(migration, parent, e)
      File "/projects/mrsarm/py/mrdev/env2.7/local/lib/python2.7/site-packages/django/db/migrations/loader.py", line 282, in _reraise_missing_dependency
        raise exc
    django.db.migrations.graph.NodeNotFoundError: Migration aldryn_bootstrap3.0001_initial dependencies reference nonexistent parent node (u'filer', u'0002_auto_20150606_2003')

**Comment by stpdev** [comment]
Strange thing. I've got just the same Django, but mine works normally...
Only difference is that I've added DjangoCMS to my project and configuret it to be with twitter bootstrap and demo data.

**Comment by FinalAngel** [comment]
@mrsarm closing this as significant improvements have been made the last couple of months
